"""
Tool Aggregator — high-level reasoning over past tools to guide innovation.

Uses the global ToolRegistry history and recent iteration results to
produce a concise "strategic summary" for injection into the Optimizer's
``additional_context``.  This gives the code-generation LLM explicit
memory of past heuristic strategies and their outcomes.

Optionally calls an **external reasoning LLM** (configured via env vars)
for deeper analysis; falls back to the default querier or a simple
template-based summary when the reasoning LLM is unavailable.

Usage::

    from LLM.tool_aggregator import ToolAggregator

    agg = ToolAggregator(registry=registry, querier=querier)
    summary = agg.summarize(
        phase="simulation",
        recent_results=runner.all_results[-5:],
        current_level="level3",
    )
    # Pass *summary* as additional_context to Optimizer.run()
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any

from .tool_registry import ToolRegistry


_PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"


def _load_aggregator_prompt() -> str:
    path = _PROMPTS_DIR / "tool_aggregator_mcts.md"
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


class ToolAggregator:
    """
    Synthesise past-tool reasoning into a strategic summary.

    Parameters
    ----------
    registry : ToolRegistry
        The global tool registry.
    querier : LLMQuerier | None
        Default querier for generating the summary.  If a dedicated
        reasoning LLM is configured (see env vars below), it will be
        used instead for the reasoning call.
    history_len : int
        How many recent tools per phase to include in the prompt.
    """

    # Env-var names for the optional external reasoning LLM
    ENV_ENABLED = "REASONING_LLM_ENABLED"
    ENV_API_URL = "REASONING_LLM_API_URL"
    ENV_MODEL   = "REASONING_LLM_MODEL"
    ENV_API_KEY = "REASONING_LLM_API_KEY"

    def __init__(
        self,
        registry: ToolRegistry,
        querier: Any | None = None,
        history_len: int = 10,
    ):
        self.registry = registry
        self.querier = querier
        self.history_len = history_len
        self._reasoning_querier: Any | None = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def summarize(
        self,
        phase: str,
        recent_results: list[dict[str, Any]] | None = None,
        current_level: str = "",
    ) -> str:
        """
        Produce a strategic summary for *phase*.

        If an LLM querier is available, the summary is generated by
        the LLM.  Otherwise a simpler template-based summary is returned.

        Returns
        -------
        str — the summary text (never None; empty string on total failure).
        """
        history_text = self.registry.format_history_context(
            phase, last_k=self.history_len
        )
        if not history_text:
            return ""

        results_text = self._format_recent_results(recent_results)
        best = self.registry.get_best(phase)
        best_text = ""
        if best and best.source_snippet:
            best_text = (
                f"Current best tool (iter {best.iteration}):\n"
                f"  Description: {best.description}\n"
                f"  Source:\n```python\n{best.source_snippet}\n```"
            )

        effective_querier = self._get_reasoning_querier()
        if effective_querier is not None:
            return self._llm_summarize(
                phase, history_text, results_text, best_text,
                current_level, effective_querier,
            )

        return self._template_summarize(
            phase, history_text, results_text, best_text, current_level,
        )

    # ------------------------------------------------------------------
    # Internal — LLM-based summary
    # ------------------------------------------------------------------

    def _llm_summarize(
        self,
        phase: str,
        history_text: str,
        results_text: str,
        best_text: str,
        current_level: str,
        querier: Any,
    ) -> str:
        template = _load_aggregator_prompt()
        if not template:
            template = _default_aggregator_prompt()

        prompt = (
            template
            .replace("{{PHASE}}", phase)
            .replace("{{LEVEL}}", current_level)
            .replace("{{HISTORY}}", history_text)
            .replace("{{RESULTS}}", results_text)
            .replace("{{BEST_TOOL}}", best_text)
        )

        try:
            result = querier.query(prompt, step_name="tool_aggregator")
            return result.get("response", "").strip()
        except Exception:
            return self._template_summarize(
                phase, history_text, results_text, best_text, current_level,
            )

    # ------------------------------------------------------------------
    # Internal — template-based fallback
    # ------------------------------------------------------------------

    def _template_summarize(
        self,
        phase: str,
        history_text: str,
        results_text: str,
        best_text: str,
        current_level: str,
    ) -> str:
        lines = [
            f"== Strategic Summary for '{phase}' (level: {current_level}) ==",
            "",
            history_text,
        ]
        if results_text:
            lines += ["", results_text]
        if best_text:
            lines += ["", best_text]
        lines += [
            "",
            "Guidance: build on the best-performing strategy above.",
            "Avoid repeating approaches that scored poorly.",
        ]
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # External reasoning LLM
    # ------------------------------------------------------------------

    def _get_reasoning_querier(self) -> Any | None:
        """
        Return the appropriate querier for the reasoning call.

        Priority:
          1. Dedicated reasoning LLM (if configured via env vars).
          2. Default querier passed at init.
          3. None (will fall back to template summary).
        """
        if self._reasoning_querier is not None:
            return self._reasoning_querier

        enabled = os.getenv(self.ENV_ENABLED, "").lower() in ("1", "true", "yes")
        if enabled:
            api_url = os.getenv(self.ENV_API_URL, "")
            model = os.getenv(self.ENV_MODEL, "")
            api_key = os.getenv(self.ENV_API_KEY, "")
            if api_url and model:
                try:
                    from .llm_querier import LLMQuerier
                    self._reasoning_querier = LLMQuerier(
                        api_keys=[api_key] if api_key else None,
                        base_url=api_url,
                        model=model,
                        session_tag="reasoning",
                    )
                    return self._reasoning_querier
                except Exception:
                    pass

        return self.querier

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _format_recent_results(results: list[dict[str, Any]] | None) -> str:
        if not results:
            return ""
        lines = ["Recent iteration results:"]
        for r in results:
            tag = ""
            if r.get("is_best"):
                tag = " [BEST]"
            elif r.get("adopted"):
                tag = " [accepted]"
            else:
                tag = " [rejected]"
            lines.append(
                f"  Iter {r.get('iteration', '?')} [{r.get('level', '?')}] "
                f"{r.get('opt_phase', '?')}: "
                f"composite={r.get('composite', 0):.4f}, "
                f"solve_rate={r.get('solve_rate', 0):.0%}"
                f"{tag} — {r.get('description', 'n/a')}"
            )
        return "\n".join(lines)


def _default_aggregator_prompt() -> str:
    return (
        "You are an expert game-AI researcher analysing MCTS heuristics.\n\n"
        "MCTS phase: {{PHASE}}\n"
        "Current level: {{LEVEL}}\n\n"
        "Below is the history of heuristic tools tried for this phase,\n"
        "including performance metrics and the current best tool.\n\n"
        "{{HISTORY}}\n\n"
        "{{RESULTS}}\n\n"
        "{{BEST_TOOL}}\n\n"
        "Produce a concise STRATEGIC SUMMARY (under 300 words, NO code):\n"
        "1. What strategies worked best and why?\n"
        "2. What strategies failed and should be avoided?\n"
        "3. What new direction or combination should be tried next?\n"
        "4. Any specific patterns from the best tool that should be\n"
        "   preserved or extended?\n\n"
        "Focus on actionable guidance for generating the next heuristic."
    )
